### ISSUE TITLE
Add disabled states to buttons on main branch

### ISSUE THREAD

**Issue by erler** [hamidra/dotdrop#122]
If inputs are empty or checkboxes are unchecked, the progress button on the card should be disabled.

We actually have it for the NFT campaign, but not in main.

**Comment by hamidra** [comment]
fixed in #121

**Comment by erler** [comment]
I'd suggest they should be disabled by default (when inputs are empty or checkboxes are unchecked). Right now they are enabled and get only disabled after clicking.
