### ISSUE TITLE
Bug Report: New Weight Classes

### ISSUE THREAD

**Issue by shawntabrizi** [hamidra/dotdrop#159]
![image](https://user-images.githubusercontent.com/1860335/193149907-c09a2853-6bb7-4ffd-8e72-24c76c4e85e0.png)

Seems like you might need to bump the Polkadot JS dependencies.

Thanks!

**Comment by hamidra** [comment]
Bumped the versions.
The apps should be fixed after these two deployments:

https://github.com/w3f-webops/gift-kusama/pull/6
https://github.com/w3f-webops/gift-polkadot/pull/6
