### ISSUE TITLE
UI Feedback Claim Gift

### ISSUE THREAD

**Issue by shawntabrizi** [hamidra/dotdrop#3]
* [x] seed phrase should be hidden until use clicks "reveal" button
* [x] Needs a page explaining creating an account
* [x] Enter address manually is not very safe, so probably not a great option
* [x] Should be able to download a password protected JSON backup of account generated

**Comment by hamidra** [comment]
**Re: Needs a page explaining creating an account:**
Added about page to explain the gift process and opened this [issue #8](https://github.com/hamidra/dotdrop/issues/8) to add account creation guide (needs design and probably some content creation)

**Re;Should be able to download a password protected JSON backup of account generated:**
needs some design, is tracked as [issue #9](https://github.com/hamidra/dotdrop/issues/9)

**Re:Enter address manually is not very safe, so probably not a great option:**
We redesigned the landing page for claim to hide this option as last resort for people who only have their account available. The app will validate the account to make sure they are valid account addresses before transferring the gift.

**Comment by hamidra** [comment]
All items are addressed.
