### ISSUE TITLE
UX - asking for permission to read accounts is premature

### ISSUE THREAD

**Issue by Swader** [hamidra/dotdrop#41]
The page asks me for permission to access my extension immediately on open, but one screen further I get to select extension, ledger, or signer account. It should only ask me for extension permission once I've selected the first option, Polkadot JS extension.

**Comment by hamidra** [comment]
Right. currently it loads the extension account when it loads the app. Need to move the to the polkadot extension connection call to after the user has selected the extension option.

**Comment by hamidra** [comment]
Should be fixed as part of #83
