### ISSUE TITLE
Layout Shift on Hide Secret Page

### ISSUE THREAD

**Issue by erler** [hamidra/dotdrop#45]
The height of the card is shifting when toggling between show and hide secret.

I'll try to position the toggle button below the phrase.

<img width="1571" alt="Screenshot 2021-05-27 at 10 51 42" src="https://user-images.githubusercontent.com/7072141/119796437-a9bf4f80-bed9-11eb-96e5-f603dd0566fc.png">
<img width="1571" alt="Screenshot 2021-05-27 at 10 51 48" src="https://user-images.githubusercontent.com/7072141/119796453-ac21a980-bed9-11eb-9b47-74ed3696dee8.png">

**Comment by hamidra** [comment]
Should fixed with new changes for copy phrase.
https://github.com/hamidra/dotdrop/commit/3997ce6cffa31b83799776560e43df32b2e2bdfe
