### ISSUE TITLE
Add favicon and metadata for Kusama campaign

### ISSUE THREAD

**Issue by erler** [hamidra/dotdrop#78]
Favicon should be the Kusama bird and title maybe something like "Kusama NFT" or "Kusama - Break the Wall" (?)
<img width="213" alt="Screenshot 2021-06-22 at 16 40 09" src="https://user-images.githubusercontent.com/7072141/122945050-94263400-d378-11eb-9d53-9ea92eeb5523.png">

**Comment by hamidra** [comment]
Resolved for both NFT and gifts
