### ISSUE TITLE
Add the option for user to be able to download the account as a JSON file

### ISSUE THREAD

**Issue by hamidra** [hamidra/dotdrop#9]
Should be able to download a password protected JSON backup of account generated

**Comment by erler** [comment]
I would like to give the users a bit more guidance here. cc @shawntabrizi 

What does the user gain by having a JSON backup? Do we recommend downloading one? Should the user choose between seed phrase and JSON backup, or is JSON an additional option?

We want to keep the overall process short and reduce the number of decisions a user has to make. I was nearly thinking whether to put this option at the account page at the very end; however, that would feel a bit detached from the flow.

**Comment by hamidra** [comment]
To me they seem to be separate independent use cases. From security standpoint, the JSON export is password protected but if user saves their seed offline on a paper or in a secure secret vault, that is probably more secure, so it depends how the users are treating their seed phrase.

Currently polkadot.js app makes the user save the json file in the last step of account creation and if they want to skip it they need to cancel the save-file popup.

![image](https://user-images.githubusercontent.com/5099795/119535394-ca9e6e00-bd3c-11eb-81be-499293580d7e.png)

[Myetherwallet](https://www.myetherwallet.com/create-wallet) has it as a separate tab which makes the UX as either seed phrase or JSON file.

![image](https://user-images.githubusercontent.com/5099795/119536069-852e7080-bd3d-11eb-92c2-355118431720.png)

I think we might neither enforce it nor making it either/or, and just offer saving the JSON file as an extra option. maybe a  download link with some info.  We should ask the user to save the 12 word phrase somewhere anyway, since they would need it if they decide to import their account to Parity-Signer or any other wallet that won't support JSON file imports.

**Comment by shawntabrizi** [comment]
@erler The JSON backup is a "safer" way to store keys on a computer as the JSON backup itself is encrypted and password protected.

This means you can easily import the account into programs like Polkadot JS Apps and Polkadot Extension, without needing to type in your seed phrase or exposing those words publicly on your computer.

I agree, for someone totally new to the space, it can be a bit more complex, but I think we should create explainer pages and help info for this kind of stuff, rather than not having the option.

If you want to try out the JSON backup stuff yourself simply go to Polkadot JS Apps

**Comment by erler** [comment]
Ok, for now I added these two steps in the Account Creation process.

<img width="1278" alt="Screenshot 2021-05-26 at 17 07 50" src="https://user-images.githubusercontent.com/7072141/119684603-edb44500-be44-11eb-8555-f6720d86807e.png">

We're having a designer specialised in security starting in June; curious to hear her opinion on that.

**Comment by shawntabrizi** [comment]
@erler I like the flow, i would simply suggest that we switch the two options so that the suggested path is to make a backup.

**Comment by hamidra** [comment]
Added the save json option with suggested option to be create json file unless user skips the step.
